#schema for the configuration file of rsvplist module
rsvplist.settings:
  type: config_object
  label: 'RSVP List Content Type Settings'
  mapping:
    allowed_types:
      types: sequence
      label: 'Content types RSVP form can display on'
      squence:
        type: string
        lable: 'Content type'